"use client";
import { useState, useEffect } from "react";
import LeftSideBar from "@/app/LeftSideBar";
import Line from "./Line";
import { ArrowBigRight } from "lucide-react";

const API_URL = "https://api.frontendexpert.io/api/fe/wordle-words";

const Wordle = () => {
  const [solution, setSolution] = useState(" - New");

  useEffect(() => {
    const fetchWord = async () => {
      const response = await fetch(API_URL);
      const words = response.json();
      const randomword = words[Math.floor(Math.random() * words.length)];
      setSolution(randomword);
    };
    fetchWord();
  }, []);

  const [guesses, setGuesses] = useState(Array(6).fill(null));

  useEffect(() => {}, []);

  return (
    <div className="md:mt-20 mt-30 mb-20">
      <div className=" p-2 w-1/5 overflow-y-auto scroll-smooth overscroll-contain">
        <LeftSideBar />
      </div>
      <div className="flex flex-col md:ml-70">
        <h1
          className="md:text-4xl text-xl font-bold dark:text-[rgb(150,150,150)] text-center 
        md:mb-5"
        >
          Play Game
          {solution}
        </h1>
        {guesses.map((guess) => (
          <Line key={guess} guess={guess} />
        ))}
        <div className="border-2 border-black h-[80vh] rounded-xl mx-2">
          <p className="text-center text-xl font-semibold text-green-900 my-5">
            Find the word which is (generated by machine) with help of the Hint
            given.
            <br /> <span className="text-red-900">You have 6 attempts.</span>
          </p>
          <div className="flex space-x-0.5">
            <div
              className="border-1 border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              U
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              N
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              D
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              E
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              R
            </div>
            <div
              className="text-white p-1 cursor-pointer bg-black/50
             dark:bg-[rgb(100,100,100)] hover:bg-black border-2 
              border-black w-10 h-10 flex items-center justify-center font-bold text-2xl"
            >
              S
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              T
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              A
            </div>
            <div
              className="text-white p-1 cursor-pointer bg-black/50
             dark:bg-[rgb(100,100,100)] hover:bg-black border-2 
              border-black w-10 h-10 flex items-center justify-center font-bold text-2xl"
            >
              N
            </div>
            <div
              className="border border-gray-600 w-10 h-10 flex items-center justify-center 
            font-bold text-2xl"
            >
              D
            </div>
            <button
              className=" bg-[rgba(38,38,23,0.25)] dark:bg-[rgb(20,20,20)] px-2 
                  hover:bg-[rgba(38,38,23,0.5)] dark:hover:bg-black p-1
                  cursor-pointer rounded flex items-center justify-center"
            >
              Enter
              <ArrowBigRight className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Wordle;
